# stages:
#   - dockertest
#   # - test

# # cache:
# #   key: ${CI_BUILD_REF_NAME}
# #   paths:
# #     - bin/

# dockertest:
#   stage: dockertest
#   only:
#     - master
#   script:
#     - go init minik8s
#     - go mod init minik8s
#     - go mod tidy
#     - go mod vendor
#     - cd test
#     - go run operate_simple_docker.go

  # tags:
  #   - minik8scicd

# test:
#   stage: test
#   only:
#     - main
#   script:
#     - ./bin/hello
#   tags:
#     - test
#缓存所有git未追踪的文件和在vendor目录下的文件
cache:
  untracked: true
  paths:
    - vendor/

stages:
  - build
  - test-tools
  - test-all

build:
  tags:
    - minik8scicd
  stage: build
  script:
    - ls -a && pwd
    - go env -w GOPROXY=https://goproxy.cn
    - go mod tidy
    - go mod vendor
    - go build ./...

test-tools:
  tags:
    - minik8scicd
  stage: test-tools
  script:
    - go mod vendor
    - go test -v ./tools/...

test:
  tags:
    - minik8scicd
  stage: test-all
  script:
    - go test -v ./...

